version: '3.5'

networks:
  frontend:
  backend:

services:
  cakes:
    image: cakeapi
    build:
      context: .\CakeAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: CakeDB
      DatabaseUser: sa
      DatabasePassword: CakeAPI(!)
      ExternalCatalogBaseUrl: http://localhost:6090
    ports:
      - "6090:80"
    container_name: cakesapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: webmvc
    container_name: webshop
    environment:
      CakeUrl: http://cakes
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5208:80"
    networks:
      - frontend
    depends_on:
      - cakes

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: CakeAPI(!)
    container_name: cakesqlserver
    ports:
      - "1448:1433"
    networks:
      - backend